spring:
  application:
    name: ums
  data:
    redis:
      host: localhost
      port: 6379
  mybatis:
    configuration:
      map-underscore-to-camel-case: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 10MB